### ISSUE TITLE
DropWizard >= 1.0.0 compability

### ISSUE THREAD

**Issue by fipp** [larrymyers/dropwizard-smtp-appender#1]
Hi, seems to be broken using DropWizard >= 1.0.0:

```
Exception in thread "main" java.lang.AbstractMethodError: com.larrymyers.SMTPAppenderFactory.build(Lch/qos/logback/classic/LoggerContext;Ljava/lang/String;Lio/dropwizard/logging/layout/LayoutFactory;Lio/dropwizard/logging/filter/LevelFilterFactory;Lio/dropwizard/logging/async/AsyncAppenderFactory;)Lch/qos/logback/core/Appender;
	at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:134)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:81)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at no.di.subscribe.SubscribeApplication.main(SubscribeApplication.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Looking at `SMTPAppenderFactory`, it seems that a method `build(LoggerContext context, String, LayoutFactory<E>, LevelFilterFactory<E>, AsyncAppenderFacory<E>)` must be overridden, whilst `build(LoggerContext context, String applicationName, Layout<ILoggingEvent> layout)` is overridden today.

**Comment by fipp** [comment]
Created a pull request here: https://github.com/larrymyers/dropwizard-smtp-appender/pulls
